version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: &weekday_schedule
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message: &commit_message
      prefix: "chore(deps)"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      <<: *weekday_schedule
      time: "03:15"
    commit-message: *commit_message

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      <<: *weekday_schedule
      time: "03:30"
    commit-message: *commit_message

  - package-ecosystem: "npm"
    directory: "/userdocs"
    schedule:
      <<: *weekday_schedule
      time: "03:45"
    commit-message: *commit_message
