version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: &weekly_schedule
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message: &commit_message
      prefix: "chore(deps)"
    groups:
      github_actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      <<: *weekly_schedule
      time: "03:15"
    open-pull-requests-limit: 10
    commit-message: *commit_message
    groups:
      cargo_dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      <<: *weekly_schedule
      time: "03:30"
    open-pull-requests-limit: 5
    commit-message: *commit_message
    groups:
      web_dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/userdocs"
    schedule:
      <<: *weekly_schedule
      time: "03:45"
    open-pull-requests-limit: 5
    commit-message: *commit_message
    groups:
      userdocs_dependencies:
        patterns:
          - "*"
