version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:15"
      timezone: "UTC"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
      time: "03:30"
      timezone: "UTC"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/userdocs"
    schedule:
      interval: "daily"
      time: "03:45"
      timezone: "UTC"
    commit-message:
      prefix: "chore(deps)"
