ignore:
  - "src/internal/proto/agenthub.internal.v1.rs"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.02%
        removed_code_behavior: fully_covered_patch

flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: bazel
      carryforward: true
    - name: rust-cargo
      carryforward: true
