// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendActorMessageRequest {
    #[prost(string, tag = "1")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from_actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to_actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub channel: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub transport: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub route_json: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub payload_json: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendActorMessageResponse {
    #[prost(int64, tag = "1")]
    pub message_id: i64,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListActorInboxRequest {
    #[prost(string, tag = "1")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub limit: i64,
    #[prost(int64, tag = "4")]
    pub after_message_id: i64,
    #[prost(bool, tag = "5")]
    pub include_delivered: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListActorInboxResponse {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<ActorMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckActorMessageRequest {
    #[prost(string, tag = "1")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub message_id: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckActorMessageResponse {
    #[prost(message, optional, tag = "1")]
    pub message: ::core::option::Option<ActorMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActorMessage {
    #[prost(int64, tag = "1")]
    pub message_id: i64,
    #[prost(string, tag = "2")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub from_actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub to_actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub channel: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub transport: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub route_json: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub payload_json: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
    #[prost(int64, tag = "10")]
    pub created_at: i64,
    #[prost(int64, tag = "11")]
    pub delivered_at: i64,
    #[prost(string, tag = "12")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransitionStepRequest {
    #[prost(string, tag = "1")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub step_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub remote_task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub output_json: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub error_text: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub input_json: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransitionStepResponse {
    #[prost(string, tag = "1")]
    pub step_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub step_key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub member_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub remote_task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub error_text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IssueNodeCredentialRequest {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag = "6")]
    pub ttl_seconds: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IssueNodeCredentialResponse {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub expires_at: i64,
    #[prost(string, tag = "5")]
    pub cert_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub key_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub ca_cert_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub security_mode: ::prost::alloc::string::String,
}
/// Generated server implementations.
pub mod team_internal_control_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TeamInternalControlServer.
    #[async_trait]
    pub trait TeamInternalControl: std::marker::Send + std::marker::Sync + 'static {
        async fn send_actor_message(
            &self,
            request: tonic::Request<super::SendActorMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendActorMessageResponse>,
            tonic::Status,
        >;
        async fn list_actor_inbox(
            &self,
            request: tonic::Request<super::ListActorInboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListActorInboxResponse>,
            tonic::Status,
        >;
        async fn ack_actor_message(
            &self,
            request: tonic::Request<super::AckActorMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AckActorMessageResponse>,
            tonic::Status,
        >;
        async fn transition_step(
            &self,
            request: tonic::Request<super::TransitionStepRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransitionStepResponse>,
            tonic::Status,
        >;
        async fn issue_node_credential(
            &self,
            request: tonic::Request<super::IssueNodeCredentialRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IssueNodeCredentialResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct TeamInternalControlServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TeamInternalControlServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TeamInternalControlServer<T>
    where
        T: TeamInternalControl,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/agenthub.internal.v1.TeamInternalControl/SendActorMessage" => {
                    #[allow(non_camel_case_types)]
                    struct SendActorMessageSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::SendActorMessageRequest>
                    for SendActorMessageSvc<T> {
                        type Response = super::SendActorMessageResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SendActorMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::send_actor_message(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendActorMessageSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/ListActorInbox" => {
                    #[allow(non_camel_case_types)]
                    struct ListActorInboxSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::ListActorInboxRequest>
                    for ListActorInboxSvc<T> {
                        type Response = super::ListActorInboxResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListActorInboxRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::list_actor_inbox(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListActorInboxSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/AckActorMessage" => {
                    #[allow(non_camel_case_types)]
                    struct AckActorMessageSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::AckActorMessageRequest>
                    for AckActorMessageSvc<T> {
                        type Response = super::AckActorMessageResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AckActorMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::ack_actor_message(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AckActorMessageSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/TransitionStep" => {
                    #[allow(non_camel_case_types)]
                    struct TransitionStepSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::TransitionStepRequest>
                    for TransitionStepSvc<T> {
                        type Response = super::TransitionStepResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TransitionStepRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::transition_step(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TransitionStepSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/IssueNodeCredential" => {
                    #[allow(non_camel_case_types)]
                    struct IssueNodeCredentialSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::IssueNodeCredentialRequest>
                    for IssueNodeCredentialSvc<T> {
                        type Response = super::IssueNodeCredentialResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IssueNodeCredentialRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::issue_node_credential(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IssueNodeCredentialSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TeamInternalControlServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "agenthub.internal.v1.TeamInternalControl";
    impl<T> tonic::server::NamedService for TeamInternalControlServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
