// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendActorMessageRequest {
    #[prost(string, tag = "1")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from_actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to_actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub channel: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub transport: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub route_json: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub payload_json: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub idempotency_key: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub from_peer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub to_peer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub channel_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendActorMessageResponse {
    #[prost(int64, tag = "1")]
    pub message_id: i64,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListActorInboxRequest {
    #[prost(string, tag = "1")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub limit: i64,
    #[prost(int64, tag = "4")]
    pub after_message_id: i64,
    #[prost(bool, tag = "5")]
    pub include_delivered: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListActorInboxResponse {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<ActorMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckActorMessageRequest {
    #[prost(string, tag = "1")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub message_id: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckActorMessageResponse {
    #[prost(message, optional, tag = "1")]
    pub message: ::core::option::Option<ActorMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActorMessage {
    #[prost(int64, tag = "1")]
    pub message_id: i64,
    #[prost(string, tag = "2")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub from_actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub to_actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub channel: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub transport: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub route_json: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub payload_json: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
    #[prost(int64, tag = "10")]
    pub created_at: i64,
    #[prost(int64, tag = "11")]
    pub delivered_at: i64,
    #[prost(string, tag = "12")]
    pub idempotency_key: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub from_peer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub to_peer_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransitionStepRequest {
    #[prost(string, tag = "1")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub step_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub remote_task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub output_json: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub error_text: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub input_json: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransitionStepResponse {
    #[prost(string, tag = "1")]
    pub step_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub step_key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub member_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub remote_task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub error_text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IssueNodeCredentialRequest {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag = "6")]
    pub ttl_seconds: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IssueNodeCredentialResponse {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub expires_at: i64,
    #[prost(string, tag = "5")]
    pub cert_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub key_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub ca_cert_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub security_mode: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub cluster_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "10")]
    pub scope: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "11")]
    pub audience: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "12")]
    pub kid: ::prost::alloc::string::String,
    #[prost(int64, tag = "13")]
    pub issued_at: i64,
    #[prost(string, tag = "14")]
    pub source_node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnsureAgentRecordRequest {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub config_json: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub source: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnsureAgentRecordResponse {
    #[prost(string, tag = "1")]
    pub agent_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAgentRecordRequest {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAgentRecordResponse {
    #[prost(string, tag = "1")]
    pub agent_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartManagedAgentRequest {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub actor_context_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartManagedAgentResponse {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopManagedAgentRequest {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopManagedAgentResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteManagedAgentRequest {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteManagedAgentResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendAgentInputRequest {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub input: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendAgentInputResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListAgentEventsRequest {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub limit: i64,
    #[prost(int64, tag = "3")]
    pub before_event_id: i64,
    #[prost(string, tag = "4")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentEventRecord {
    #[prost(int64, tag = "1")]
    pub event_id: i64,
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub seq: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub ts: i64,
    #[prost(string, tag = "6")]
    pub stream: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAgentEventsResponse {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<AgentEventRecord>,
}
/// Generated client implementations.
pub mod team_internal_control_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct TeamInternalControlClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TeamInternalControlClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TeamInternalControlClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TeamInternalControlClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TeamInternalControlClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn send_actor_message(
            &mut self,
            request: impl tonic::IntoRequest<super::SendActorMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendActorMessageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/SendActorMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "SendActorMessage",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_actor_inbox(
            &mut self,
            request: impl tonic::IntoRequest<super::ListActorInboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListActorInboxResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/ListActorInbox",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "ListActorInbox",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn ack_actor_message(
            &mut self,
            request: impl tonic::IntoRequest<super::AckActorMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AckActorMessageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/AckActorMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "AckActorMessage",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn transition_step(
            &mut self,
            request: impl tonic::IntoRequest<super::TransitionStepRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransitionStepResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/TransitionStep",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "TransitionStep",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn issue_node_credential(
            &mut self,
            request: impl tonic::IntoRequest<super::IssueNodeCredentialRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IssueNodeCredentialResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/IssueNodeCredential",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "IssueNodeCredential",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn ensure_agent_record(
            &mut self,
            request: impl tonic::IntoRequest<super::EnsureAgentRecordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EnsureAgentRecordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/EnsureAgentRecord",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "EnsureAgentRecord",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_agent_record(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAgentRecordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAgentRecordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/GetAgentRecord",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "GetAgentRecord",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn start_managed_agent(
            &mut self,
            request: impl tonic::IntoRequest<super::StartManagedAgentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartManagedAgentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/StartManagedAgent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "StartManagedAgent",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn stop_managed_agent(
            &mut self,
            request: impl tonic::IntoRequest<super::StopManagedAgentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StopManagedAgentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/StopManagedAgent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "StopManagedAgent",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_managed_agent(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteManagedAgentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteManagedAgentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/DeleteManagedAgent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "DeleteManagedAgent",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn send_agent_input(
            &mut self,
            request: impl tonic::IntoRequest<super::SendAgentInputRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendAgentInputResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/SendAgentInput",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "SendAgentInput",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_agent_events(
            &mut self,
            request: impl tonic::IntoRequest<super::ListAgentEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListAgentEventsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agenthub.internal.v1.TeamInternalControl/ListAgentEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "agenthub.internal.v1.TeamInternalControl",
                        "ListAgentEvents",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod team_internal_control_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TeamInternalControlServer.
    #[async_trait]
    pub trait TeamInternalControl: std::marker::Send + std::marker::Sync + 'static {
        async fn send_actor_message(
            &self,
            request: tonic::Request<super::SendActorMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendActorMessageResponse>,
            tonic::Status,
        >;
        async fn list_actor_inbox(
            &self,
            request: tonic::Request<super::ListActorInboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListActorInboxResponse>,
            tonic::Status,
        >;
        async fn ack_actor_message(
            &self,
            request: tonic::Request<super::AckActorMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AckActorMessageResponse>,
            tonic::Status,
        >;
        async fn transition_step(
            &self,
            request: tonic::Request<super::TransitionStepRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransitionStepResponse>,
            tonic::Status,
        >;
        async fn issue_node_credential(
            &self,
            request: tonic::Request<super::IssueNodeCredentialRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IssueNodeCredentialResponse>,
            tonic::Status,
        >;
        async fn ensure_agent_record(
            &self,
            request: tonic::Request<super::EnsureAgentRecordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EnsureAgentRecordResponse>,
            tonic::Status,
        >;
        async fn get_agent_record(
            &self,
            request: tonic::Request<super::GetAgentRecordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAgentRecordResponse>,
            tonic::Status,
        >;
        async fn start_managed_agent(
            &self,
            request: tonic::Request<super::StartManagedAgentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartManagedAgentResponse>,
            tonic::Status,
        >;
        async fn stop_managed_agent(
            &self,
            request: tonic::Request<super::StopManagedAgentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StopManagedAgentResponse>,
            tonic::Status,
        >;
        async fn delete_managed_agent(
            &self,
            request: tonic::Request<super::DeleteManagedAgentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteManagedAgentResponse>,
            tonic::Status,
        >;
        async fn send_agent_input(
            &self,
            request: tonic::Request<super::SendAgentInputRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendAgentInputResponse>,
            tonic::Status,
        >;
        async fn list_agent_events(
            &self,
            request: tonic::Request<super::ListAgentEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListAgentEventsResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct TeamInternalControlServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TeamInternalControlServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TeamInternalControlServer<T>
    where
        T: TeamInternalControl,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/agenthub.internal.v1.TeamInternalControl/SendActorMessage" => {
                    #[allow(non_camel_case_types)]
                    struct SendActorMessageSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::SendActorMessageRequest>
                    for SendActorMessageSvc<T> {
                        type Response = super::SendActorMessageResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SendActorMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::send_actor_message(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendActorMessageSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/ListActorInbox" => {
                    #[allow(non_camel_case_types)]
                    struct ListActorInboxSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::ListActorInboxRequest>
                    for ListActorInboxSvc<T> {
                        type Response = super::ListActorInboxResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListActorInboxRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::list_actor_inbox(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListActorInboxSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/AckActorMessage" => {
                    #[allow(non_camel_case_types)]
                    struct AckActorMessageSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::AckActorMessageRequest>
                    for AckActorMessageSvc<T> {
                        type Response = super::AckActorMessageResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AckActorMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::ack_actor_message(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AckActorMessageSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/TransitionStep" => {
                    #[allow(non_camel_case_types)]
                    struct TransitionStepSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::TransitionStepRequest>
                    for TransitionStepSvc<T> {
                        type Response = super::TransitionStepResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TransitionStepRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::transition_step(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TransitionStepSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/IssueNodeCredential" => {
                    #[allow(non_camel_case_types)]
                    struct IssueNodeCredentialSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::IssueNodeCredentialRequest>
                    for IssueNodeCredentialSvc<T> {
                        type Response = super::IssueNodeCredentialResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IssueNodeCredentialRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::issue_node_credential(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IssueNodeCredentialSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/EnsureAgentRecord" => {
                    #[allow(non_camel_case_types)]
                    struct EnsureAgentRecordSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::EnsureAgentRecordRequest>
                    for EnsureAgentRecordSvc<T> {
                        type Response = super::EnsureAgentRecordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EnsureAgentRecordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::ensure_agent_record(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EnsureAgentRecordSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/GetAgentRecord" => {
                    #[allow(non_camel_case_types)]
                    struct GetAgentRecordSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::GetAgentRecordRequest>
                    for GetAgentRecordSvc<T> {
                        type Response = super::GetAgentRecordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAgentRecordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::get_agent_record(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAgentRecordSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/StartManagedAgent" => {
                    #[allow(non_camel_case_types)]
                    struct StartManagedAgentSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::StartManagedAgentRequest>
                    for StartManagedAgentSvc<T> {
                        type Response = super::StartManagedAgentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StartManagedAgentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::start_managed_agent(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StartManagedAgentSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/StopManagedAgent" => {
                    #[allow(non_camel_case_types)]
                    struct StopManagedAgentSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::StopManagedAgentRequest>
                    for StopManagedAgentSvc<T> {
                        type Response = super::StopManagedAgentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StopManagedAgentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::stop_managed_agent(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StopManagedAgentSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/DeleteManagedAgent" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteManagedAgentSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::DeleteManagedAgentRequest>
                    for DeleteManagedAgentSvc<T> {
                        type Response = super::DeleteManagedAgentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteManagedAgentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::delete_managed_agent(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteManagedAgentSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/SendAgentInput" => {
                    #[allow(non_camel_case_types)]
                    struct SendAgentInputSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::SendAgentInputRequest>
                    for SendAgentInputSvc<T> {
                        type Response = super::SendAgentInputResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SendAgentInputRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::send_agent_input(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendAgentInputSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agenthub.internal.v1.TeamInternalControl/ListAgentEvents" => {
                    #[allow(non_camel_case_types)]
                    struct ListAgentEventsSvc<T: TeamInternalControl>(pub Arc<T>);
                    impl<
                        T: TeamInternalControl,
                    > tonic::server::UnaryService<super::ListAgentEventsRequest>
                    for ListAgentEventsSvc<T> {
                        type Response = super::ListAgentEventsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListAgentEventsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TeamInternalControl>::list_agent_events(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListAgentEventsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TeamInternalControlServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "agenthub.internal.v1.TeamInternalControl";
    impl<T> tonic::server::NamedService for TeamInternalControlServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
