[source."ssh://git@github.com/JakkuSakura/tungstenite-rs.git"]
replace-with = "tungstenite-rs-https"

[source.tungstenite-rs-https]
git = "https://github.com/JakkuSakura/tungstenite-rs.git"
branch = "proxy-support"
